### PR TITLE
Moodle 23 stable Update format.php for Moodle2.4

### PR DESCRIPTION
**Pull request by roelmann**
Update format.php to work with Moodle2.4

### CODE REVIEW

**Comment by gjb2048** [comment]
Richard,

Did you solve the image issue to?

Cheers,

Gareth

**Comment by roelmann** [comment]
not yet Gareth, after a very quick look, it went on the back-burner while I'm testing the rest of our plugins and code changes with 2.4.
I think its something to do with the way the file-picker is bringing images in though, as courses that already had png files in the grid work fine (for the existing images) but I cant add pngs to the grid now. I'll try to take another look in the next couple of days and see if I can track it down.
Richard

**Comment by gjb2048** [comment]
Thanks Richard :)

There has been a request to update the format to 2.4 and I was going to see if I had time and wondered how far you had got as I did not want to repeat what you had already done :) - as always, time and money, time and money... :D

Cheers,
Gareth

**Comment by danbuntu** [comment]
Any news on this? Our tutors love this module and I would really like to get cracking on moodle 2.4

**Comment by gjb2048** [comment]
Dear Danbuntu,

Not yet.  I've been ill and I need to complete some other work on my own course format first.  Would you have funding to sponsor the upgrade?

Cheers,

Gareth

**Comment by danbuntu** [comment]
No funding I'm afraid. But I'm a developer and might be able to help test or fix issues if I'm pointed in the right direction.

**Comment by gjb2048** [comment]
Dear Danbuntu,

Ok, thanks.  The issue here is the png issue Richard has encountered for which I have yet to fix.  If you have a spare moment and download the latest 2.3 version, apply Richards patch and see if you can see what is wrong with png files then that would be appreciated.  If you encounter any other 2.4 upgrade issues, then yet me know as I now know the changes for 2.4 course formats inside out.

Cheers,

Gareth

**Comment by gjb2048** [comment]
Dear all,

I've made a start on the format for 2.4 on - https://github.com/gjb2048/moodle-courseformat_grid/tree/MOODLE_24_STABLE -.  I've figured out a bit of the png issue being from the quality in editimage.png.  However, the images are not displaying.  Through debugging I've discovered that the images are being converted and stored and dished out (hopefully the right byte stream) by 'readfile_accel' in '/lib/filelib.php' with the correct mime type.  However Chrome does not display them and Firefox reports that the image cannot be displayed because it contains errors - when you use the 'pluginfile.php' url embedded on the page.

Cheers,

Gareth

**Comment by nadavkav** [comment]
Just found out about this issue too :( (after upgrading to Moodle 2.4)
I have joined the digging party. Hope to come up with an answer soon :-)
(We have several courses using this beautiful!!! course format, and the teachers are...)

**Comment by gjb2048** [comment]
Dear Nadav,

What's the issue as a lot has happened since then?  Like it works for 2.4 https://github.com/gjb2048/moodle-courseformat_grid/tree/MOODLE_24_STABLE

Cheers,

Gareth

**Comment by nadavkav** [comment]
Me bad :-(
Was using the wrong branch (installed it as submodule and forgot to update)
Please ignore :-)

**Pull request merged**
